<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>Reçu {{ $document->numero }}</title>@include('pdf._style')</head><body>
@include('pdf._header')
<table class="doc-head"><tr><td><div class="eyebrow">Paiement enregistré</div><h1 class="title">Reçu de paiement</h1></td><td class="number">Reçu n°<strong>{{ $document->numero }}</strong>Émis le {{ $document->date_emission->format('d/m/Y') }}</td></tr></table>
<table class="party"><tr><td><div class="label">Reçu de</div><div class="party-name">{{ strtoupper($versement->inscription->etudiant->nom) }} {{ $versement->inscription->etudiant->prenom }}</div>{{ $versement->inscription->etudiant->email }}<br>{{ $versement->inscription->etudiant->telephone ?: 'Téléphone non renseigné' }}</td><td><div class="label">Dossier académique</div><div class="party-name">{{ $versement->inscription->formation->code }}</div>Année {{ $versement->inscription->anneeAcademique->libelle }}<br>Inscription n° {{ $versement->inscription_id }}</td></tr></table>
<div class="amount-highlight"><span>Montant reçu</span><strong>{{ number_format($document->montant_paye,0,',',' ') }} MRU</strong></div>
<table class="grid"><tr><th>Détail du règlement</th><th>Mode</th><th>Référence</th><th class="right">Montant</th></tr><tr><td>Paiement des frais de formation<br><span class="payment-status">Paiement validé</span></td><td>{{ $versement->mode_paiement }}</td><td>{{ $versement->reference ?: 'Non renseignée' }}</td><td class="right"><strong>{{ number_format($document->montant_paye,0,',',' ') }} MRU</strong></td></tr></table>
<table class="summary"><tr><td>Frais nets du dossier</td><td class="right">{{ number_format($document->montant_total,0,',',' ') }} MRU</td></tr><tr><td>Total versé après ce paiement</td><td class="right">{{ number_format($document->details['total_verse_apres_paiement'] ?? ($document->montant_total-$document->solde_restant),0,',',' ') }} MRU</td></tr><tr class="grand"><td>Solde restant</td><td class="right">{{ number_format($document->solde_restant,0,',',' ') }} MRU</td></tr></table>
<div class="legal-note">Ce reçu confirme l'enregistrement du paiement ci-dessus dans le dossier financier de l'étudiant. Il doit être conservé comme justificatif.</div>
<table class="signature-row"><tr><td></td><td><div class="stamp-frame"><img src="{{ public_path('images/cachet-signature-insec.jpg') }}" alt="Cachet et signature INSEC"></div><div class="signature-caption">Cachet et signature de l'INSEC</div></td></tr></table>
<div class="footer">INSEC - Institut d'expertise comptable, Nouakchott <span class="right-footer">Document {{ $document->numero }}</span></div>
</body></html>
