services:
  - type: web
    name: insec-dashboard
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health/live
    envVars:
      - key: APP_NAME
        value: INSEC Dashboard
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        sync: false
      - key: FILESYSTEM_DRIVER
        value: s3
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        sync: false
      - key: AWS_BUCKET
        value: dossiers-insec
      - key: AWS_ENDPOINT
        sync: false
      - key: AWS_USE_PATH_STYLE_ENDPOINT
        value: "true"
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: MAIL_MAILER
        value: log
