<x-app-layout><div class="flex min-h-screen bg-gray-100">@include('partials.sidebar')
<main class="flex-1 p-6 lg:p-8 min-w-0">
    <div class="mb-5"><p class="text-sm text-gray-500">Enseignement et progression</p><h1 class="text-2xl font-bold text-[#1E2761]">Académique</h1><p class="text-sm text-gray-500 mt-1">Retrouvez le catalogue, les enseignants et les résultats au même endroit.</p></div>
    <form method="GET" class="mb-6 flex flex-wrap items-center gap-3 rounded-xl border border-amber-200 bg-amber-50 p-3 max-w-5xl"><label class="text-sm font-semibold text-[#1E2761]">Année académique</label><select name="annee_id" onchange="this.form.submit()" class="rounded-lg border-amber-300 text-sm font-semibold text-[#1E2761]">@foreach($annees as $annee)<option value="{{ $annee->id }}" @selected($anneeId===$annee->id)>{{ $annee->libelle }}</option>@endforeach</select><span class="text-xs text-gray-500">{{ $statistiques['etudiants'] }} étudiant(s) · {{ $statistiques['examens'] }} examen(s) · {{ $statistiques['resultats'] }} résultat(s)</span></form>
    <div class="grid md:grid-cols-3 gap-5 max-w-5xl">
        <a href="{{ route('formations.index') }}" class="bg-white border rounded-xl p-6 hover:border-[#D4AF37]"><span class="w-11 h-11 rounded-lg bg-amber-50 text-amber-700 flex items-center justify-center"><i class="fa-solid fa-book-open"></i></span><h2 class="font-bold text-[#1E2761] mt-5">Diplômes et UE</h2><p class="text-sm text-gray-500 mt-2">Consulter le catalogue DGC et DSGC, les parcours et les crédits.</p><span class="inline-block mt-5 text-sm font-semibold text-[#1E2761]">Ouvrir →</span></a>
        <a href="{{ route('enseignants.index') }}" class="bg-white border rounded-xl p-6 hover:border-[#D4AF37]"><span class="w-11 h-11 rounded-lg bg-blue-50 text-blue-700 flex items-center justify-center"><i class="fa-solid fa-chalkboard-user"></i></span><h2 class="font-bold text-[#1E2761] mt-5">Enseignants</h2><p class="text-sm text-gray-500 mt-2">Gérer les enseignants et leurs affectations aux unités d’enseignement.</p><span class="inline-block mt-5 text-sm font-semibold text-[#1E2761]">Ouvrir →</span></a>
        <a href="{{ route('examens.index', ['annee_id' => $anneeId]) }}" class="bg-white border rounded-xl p-6 hover:border-[#D4AF37]"><span class="w-11 h-11 rounded-lg bg-purple-50 text-purple-700 flex items-center justify-center"><i class="fa-solid fa-clipboard-check"></i></span><h2 class="font-bold text-[#1E2761] mt-5">Examens et résultats</h2><p class="text-sm text-gray-500 mt-2">Planifier les sessions, saisir les notes et suivre les validations de l’année sélectionnée.</p><span class="inline-block mt-5 text-sm font-semibold text-[#1E2761]">Ouvrir →</span></a>
    </div>
</main></div></x-app-layout>
