<!DOCTYPE html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Préinscription INSEC</title>@vite(['resources/css/app.css','resources/js/app.js'])</head><body class="bg-gray-50 text-gray-800">
<header class="bg-[#1E2761] text-white"><div class="max-w-5xl mx-auto px-6 py-5 flex justify-between items-center"><strong class="text-xl">INSEC</strong><a href="{{ route('login') }}" class="text-sm bg-white/10 px-4 py-2 rounded-lg">Espace connecté</a></div></header>
<main class="max-w-3xl mx-auto p-6 py-10"><div class="mb-7"><p class="text-sm font-semibold text-[#D4AF37]">DGC · DSGC — INTEC CNAM</p><h1 class="text-3xl font-bold text-[#1E2761] mt-1">Demande de préinscription</h1><p class="text-gray-500 mt-2">Déposez votre candidature. L’équipe INSEC étudiera votre dossier avant toute inscription définitive.</p></div>
@if($errors->any())<div class="bg-red-50 text-red-800 rounded-lg p-4 mb-5"><ul class="list-disc pl-5">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('candidatures.store') }}" class="bg-white border rounded-2xl shadow-sm p-6 space-y-5">@csrf
<div class="grid md:grid-cols-2 gap-4">@foreach([['prenom','Prénom','text'],['nom','Nom','text'],['email','Adresse e-mail','email'],['telephone','Téléphone','text'],['date_naissance','Date de naissance','date'],['dernier_diplome','Dernier diplôme obtenu','text']] as $f)<label class="text-sm text-gray-600">{{ $f[1] }}<input type="{{ $f[2] }}" name="{{ $f[0] }}" value="{{ old($f[0]) }}" class="w-full mt-1 rounded-lg border-gray-300" {{ $f[0]==='date_naissance'?'':'required' }}></label>@endforeach
<label class="text-sm text-gray-600">Diplôme visé<select name="formation_id" required class="w-full mt-1 rounded-lg border-gray-300"><option value="">Sélectionner…</option>@foreach($formations as $f)<option value="{{ $f->id }}" @selected(old('formation_id')==$f->id)>{{ $f->code }} — {{ $f->libelle }}</option>@endforeach</select></label>
<label class="text-sm text-gray-600">Année académique<select name="annee_academique_id" required class="w-full mt-1 rounded-lg border-gray-300">@foreach($annees as $a)<option value="{{ $a->id }}" @selected(old('annee_academique_id')==$a->id)>{{ $a->libelle }}</option>@endforeach</select></label></div>
<label class="text-sm text-gray-600 block">Motivation <span class="text-gray-400">(facultatif)</span><textarea name="motivation" rows="4" maxlength="2000" class="w-full mt-1 rounded-lg border-gray-300">{{ old('motivation') }}</textarea></label>
<label class="flex gap-2 text-sm text-gray-600"><input type="checkbox" required class="rounded border-gray-300 mt-1"><span>Je certifie l’exactitude des informations transmises et autorise leur traitement pour ma demande d’admission.</span></label>
<button class="w-full bg-[#1E2761] text-white font-semibold py-3 rounded-lg hover:bg-[#151b45]">Envoyer ma candidature</button></form></main></body></html>
